name: Quick URL Fixes

on:
  workflow_dispatch:

jobs:
  fix-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install pandas
    - name: Fix additional URLs
      run: python quick_url_fixes.py
    - name: Commit fixed CSV
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add companies_final_ready.csv
        if ! git diff --staged --quiet; then
          git commit -m "🔧 Fixed additional URLs for 8 companies"
          git push
        fi
